"use client";

import React, { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import { Clock, FileText, Video, PhoneCall, Mic, Bot } from 'lucide-react';
import { VoiceRecorder } from '@/components/VoiceRecorder';

interface TimelineEvent {
  id: number;
  event_time: string;
  description: string;
  source_type: string;
}

export default function CaseTimelinePage() {
  const params = useParams();
  const caseId = parseInt(params.id as string) || 1; // Default to 1 if not provided
  
  const [events, setEvents] = useState<TimelineEvent[]>([]);
  const [loading, setLoading] = useState(true);

  const fetchTimeline = async () => {
    setLoading(true);
    try {
      const res = await fetch(`http://localhost:8000/copilot/timeline/${caseId}`);
      const data = await res.json();
      setEvents(data.events || []);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchTimeline();
  }, [caseId]);

  const handleRecordingComplete = (noteId: number, transcript: string) => {
    // Refresh timeline when a new note is added
    fetchTimeline();
  };

  const getIcon = (sourceType: string) => {
    switch (sourceType) {
      case 'VoiceNote': return <Mic className="w-5 h-5 text-white" />;
      case 'FIR': return <FileText className="w-5 h-5 text-white" />;
      case 'WitnessStatement': return <PhoneCall className="w-5 h-5 text-white" />;
      default: return <Clock className="w-5 h-5 text-white" />;
    }
  };

  const getColor = (sourceType: string) => {
    switch (sourceType) {
      case 'VoiceNote': return 'bg-blue-500';
      case 'FIR': return 'bg-red-500';
      case 'WitnessStatement': return 'bg-orange-500';
      default: return 'bg-purple-500';
    }
  };

  return (
    <div className="space-y-6 max-w-5xl mx-auto pb-20">
      <div>
        <h1 className="text-3xl font-bold tracking-tight flex items-center gap-2">
          <Clock className="w-8 h-8 text-blue-600" /> Case {caseId} Timeline
        </h1>
        <p className="text-muted-foreground mt-1">Automatic investigation timeline generated by AI.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="md:col-span-2 bg-white dark:bg-slate-900 border rounded-xl p-6 shadow-sm">
          <h2 className="text-xl font-bold mb-6 flex items-center gap-2">
            <Bot size={24} className="text-blue-500" /> Auto-Generated Sequence
          </h2>
          
          {loading ? (
            <div className="text-center p-10 text-slate-500 animate-pulse">Loading timeline events...</div>
          ) : events.length === 0 ? (
            <div className="text-center p-10 text-slate-500">No events recorded for this case yet.</div>
          ) : (
            <div className="relative">
              <div className="absolute left-[39px] top-4 bottom-4 w-0.5 bg-slate-200 dark:bg-slate-800"></div>
              <div className="space-y-8">
                {events.map((event, i) => {
                  const dateObj = new Date(event.event_time);
                  return (
                    <div key={i} className="flex gap-6 relative">
                      <div className="w-16 text-right pt-2 flex-shrink-0">
                        <div className="font-bold text-sm text-slate-900 dark:text-slate-100">
                          {dateObj.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                        </div>
                        <div className="text-xs text-slate-500">
                          {dateObj.toLocaleDateString([], { month: 'short', day: 'numeric' })}
                        </div>
                      </div>
                      
                      <div className={`w-10 h-10 rounded-full ${getColor(event.source_type)} flex items-center justify-center flex-shrink-0 relative z-10 border-4 border-white dark:border-slate-900 shadow-sm`}>
                        {getIcon(event.source_type)}
                      </div>
                      
                      <div className="bg-slate-50 dark:bg-slate-800 border rounded-xl p-4 flex-1 shadow-sm">
                        <div className="flex justify-between items-start mb-2">
                          <h4 className="font-semibold text-md">{event.description}</h4>
                        </div>
                        <div className="mt-3 pt-3 border-t border-slate-200 dark:border-slate-700 flex gap-2">
                          <span className="text-[10px] uppercase font-bold bg-blue-100 text-blue-700 dark:bg-blue-900 dark:text-blue-300 px-2 py-1 rounded">
                            Source: {event.source_type}
                          </span>
                        </div>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          )}
        </div>

        <div className="md:col-span-1 space-y-6">
          <VoiceRecorder caseId={caseId} userId={1} onRecordingComplete={handleRecordingComplete} />
          
          <div className="bg-white dark:bg-slate-900 border rounded-xl p-5 shadow-sm">
            <h3 className="font-semibold mb-3 flex items-center gap-2">
              <FileText size={18} /> Generate Report
            </h3>
            <p className="text-xs text-slate-500 mb-4">Export the timeline and AI case summary as a PDF document.</p>
            <button className="w-full bg-slate-900 dark:bg-slate-100 text-white dark:text-slate-900 text-sm font-medium py-2 rounded-lg hover:opacity-90 transition">
              Download Case Briefing
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
